import Navigations from "@/components/optionavigations";
export const metadata = {
  title: "Next.js App",
  description: "Generated by Next.js",
};

export default function IndexLayout({ children }) {
  return (
    <>
    <Navigations/>
    <main>{children}</main>
    </>
  );
}

  